### ISSUE TITLE
잔류제도 폐지 관련 FAQ 수정

### ISSUE THREAD

**Issue by key-del-jeeinho** [themoment-team/hello-gsm-front#107]
![image](https://user-images.githubusercontent.com/77221262/184565487-3a12a94d-b8f7-46a8-b8d0-58898ad02cfc.png)
현재 설명에 타시도 학생은 2주에 1번 퇴소한다고 작성되어있는데, 잔류제도가 폐지되어 타시도학생도 매주 퇴소하는것으로 알고 있습니다. 이부분에 대한 수정이 필요해보여요.

**Comment by yoosion030** [comment]
예전 질문과 답변들을 모아서 그런지 잘못된 내용이 포함된 것 같습니다. 모든 FAQ를 검토한 후 수정하겠습니다. 제보해주셔서 감사합니다 👏
