### ISSUE TITLE
회원가입시 생년월일입력 관련 이슈

### ISSUE THREAD

**Issue by key-del-jeeinho** [themoment-team/hello-gsm-front#99]
![image](https://user-images.githubusercontent.com/77221262/182756597-1f0d419a-4ac6-4094-ab2e-7de6d493a78a.png)
생년월일을 입력해도 회원가입 버튼 클릭시
- 1월 에highlighting된 상태로
- `생년월일을 선택해주세요` 라는 Error Writing이 표시되며 

회원가입 이 되지 않습니다.
테스트 해본 날짜는 아래와 같습니다.
- 2005년 1월 3일
- 2007년 1월 3일
- 2008년 1월 3일

이후, 월을 2월로 변경 후 재수행하니 회원가입이 완료되었다고 뜹니다.
Window11, Chrome 브라우저를 사용하고있습니다.
좋은 서비스 만들어주셔서 감사합니다 🙂

**Comment by yoosion030** [comment]
값을 예외처리 하던 도중 에러가 발생했던걸로 보입니다. 덕분에 문제를 인식하고 곧바로 수정하였습니다. 저희 서비스에 관심 가져주시고 제보해주셔서 감사합니다 :)
